<script lang="ts">
	import { Database, Shield, Eye, Layers } from 'lucide-svelte';
	import { tilt } from '$lib/actions/tilt';
	import { intersect } from '$lib/actions/intersect';

	let visible = $state(false);
</script>

<section
	id="features"
	class="relative py-24 px-6"
	use:intersect={{ threshold: 0.1, onIntersect: () => { visible = true; } }}
>
	<div class="max-w-5xl mx-auto">
		<!-- Section header -->
		<div class="flex items-baseline justify-between mb-8">
			<h2 class="text-3xl sm:text-4xl font-light tracking-tight text-white">Core Architecture</h2>
			<span class="text-sm text-neutral-500 hidden sm:block">System Overview</span>
		</div>

		<div class="grid grid-cols-1 md:grid-cols-3 auto-rows-[300px] gap-4">
			<!-- Card 1: Total Recall Vector Store (2-col span, featured with border-beam) -->
			<div
				class="relative md:col-span-2 rounded-xl border border-neutral-800 bg-neutral-900/60 p-6 flex flex-col justify-between overflow-hidden transition-all duration-500 {visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}"
				style="transition-delay: 0ms"
				use:tilt={{ max: 4, scale: 1.005 }}
			>

				<div>
					<div class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-neutral-800/60 text-neutral-400">
						<Database class="w-5 h-5" />
					</div>
					<h3 class="text-lg font-medium text-neutral-200 mb-2">Total Recall Vector Store</h3>
					<p class="text-sm text-neutral-500 leading-relaxed max-w-md">
						384-dimensional embeddings generated by all-MiniLM-L6-v2 stored in Dexie.js over IndexedDB.
						Sub-50ms cosine similarity search across your entire browsing history.
					</p>
				</div>
				<div class="flex gap-2 flex-wrap">
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">384-dim vectors</span>
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">all-MiniLM-L6-v2</span>
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">IndexedDB</span>
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">Dexie.js</span>
				</div>
			</div>

			<!-- Card 2: Zero Egress -->
			<div
				class="rounded-xl border border-neutral-800 bg-neutral-900/60 p-6 flex flex-col justify-between transition-all duration-500 {visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}"
				style="transition-delay: 100ms"
				use:tilt={{ max: 6, scale: 1.01 }}
			>
				<div>
					<div class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-neutral-800/60 text-neutral-400">
						<Shield class="w-5 h-5" />
					</div>
					<h3 class="text-lg font-medium text-neutral-200 mb-2">Zero Egress</h3>
					<p class="text-sm text-neutral-500 leading-relaxed">
						Transformers.js runs ONNX models in WASM — zero network requests for inference. Your data never leaves the browser.
					</p>
				</div>
				<div class="flex gap-2 flex-wrap">
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">Transformers.js</span>
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">ONNX WASM</span>
				</div>
			</div>

			<!-- Card 3: Smart Extraction -->
			<div
				class="rounded-xl border border-neutral-800 bg-neutral-900/60 p-6 flex flex-col justify-between transition-all duration-500 {visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}"
				style="transition-delay: 200ms"
				use:tilt={{ max: 6, scale: 1.01 }}
			>
				<div>
					<div class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-neutral-800/60 text-neutral-400">
						<Eye class="w-5 h-5" />
					</div>
					<h3 class="text-lg font-medium text-neutral-200 mb-2">Smart Extraction</h3>
					<p class="text-sm text-neutral-500 leading-relaxed">
						Site-specific extractors for YouTube, Amazon, Reddit, and X. Five event types capture rich context from every interaction.
					</p>
				</div>
				<div class="flex gap-2 flex-wrap">
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">5 event types</span>
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">4 extractors</span>
				</div>
			</div>

			<!-- Card 4: Cross-Platform Knowledge (2-col span) -->
			<div
				class="md:col-span-2 rounded-xl border border-neutral-800 bg-neutral-900/60 p-6 flex flex-col justify-between transition-all duration-500 {visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}"
				style="transition-delay: 300ms"
				use:tilt={{ max: 4, scale: 1.005 }}
			>
				<div>
					<div class="mb-4 flex h-10 w-10 items-center justify-center rounded-lg bg-neutral-800/60 text-neutral-400">
						<Layers class="w-5 h-5" />
					</div>
					<h3 class="text-lg font-medium text-neutral-200 mb-2">Cross-Platform Knowledge</h3>
					<p class="text-sm text-neutral-500 leading-relaxed max-w-md">
						Automatic interaction tracking across sites. Pages, videos, purchases, likes, and bookmarks unified into a single searchable knowledge base.
					</p>
				</div>
				<div class="flex gap-2 flex-wrap">
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">YouTube</span>
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">Amazon</span>
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">Reddit</span>
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">X</span>
					<span class="text-[11px] px-2.5 py-1 rounded-full border border-neutral-700 bg-neutral-800/60 text-neutral-400">Generic</span>
				</div>
			</div>
		</div>
	</div>
</section>
